repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

  - repo: local
    hooks:
    -   id: ruff-format
        name: Autoformat python code
        language: system
        entry: pixi
        args: [run, format]
        pass_filenames: false

  - repo: local
    hooks:
    -   id: ruff-lint
        name: Lint python code
        language: system
        entry: pixi
        args: [run, lint]
        pass_filenames: false

  - repo: local
    hooks:
    -   id: mypy
        name: Type check python code
        language: system
        entry: pixi
        args: [run, type-check]
        pass_filenames: false
