name: descent-workflow

channels:
  - conda-forge
  - openeye
  - bioconda

dependencies:

  - python >=3.10
  - pip

  - smee    >=0.8.0
  - descent >=0.4.0

  - click
  - more-itertools

  # Workflow
  - snakemake
  - loguru
  - seaborn

  # Parameterization
  - openff-toolkit
  - openff-interchange
  - rdkit
  - openeye-toolkits

  # Training
  - tensorboard
  - tensorboardX
  - tbparse

  # Benchmarking
  - openff-qcsubmit
  - click-option-group
  - dask
  - dask-jobqueue
  - geometric

  # Interface with Espaloma
  - dgl

  # Dev
  - pre-commit
  - ruff
  - mypy

# New versions of torchdata require new versions of PyTorch which are not supported by DGL
  - torchdata<=0.10.0

# Pip
  - pip:
      - git+https://github.com/thomasjamespope/smee.git
      - git+https://github.com/openforcefield/yammbs.git
      - deepchem
